# Generated by Django 3.2.14 on 2022-08-02 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tittle',
            new_name='title',
        ),
    ]
